// --- START OF FILE i18n/declarationTranslations.ts ---
export const declarationTranslations = {
  en: {
    centerTitle: "Support & Declarations",
    newTicket: "New Declaration",
    aiPrompt: "Describe your issue...",
    aiButton: "Auto-Detect",
    categories: "Or choose a category",
    reviewTitle: "Official Declaration Summary",
    reviewSub: "Generated by Al-Wassit AI",
    confirmBtn: "Sign & Submit",
    cats: {
      TRANSACTION: "Transaction Issue",
      FRAUD_SECURITY: "Fraud & Security",
      ACCOUNT: "Account Problem",
      LOAN_CONTRACT: "Loan Disputes",
      TECH_ISSUE: "App Bug",
      REPORT_USER: "Report User",
      KYC_UPDATE: "ID/KYC Update",
      GENERAL: "General Help"
    }
  },
  dz: {
    centerTitle: "Markaz Chkawi",
    newTicket: "Chkaya Jdida",
    aiPrompt: "Ahkili wach sar...",
    aiButton: "Detecter el Mouchkil",
    categories: "Wella kher Categorie",
    reviewTitle: "Moulakhas Rasmi",
    reviewSub: "Mektoub b'AI",
    confirmBtn: "Sinyi w Eb3at",
    cats: {
      TRANSACTION: "Mouchkil Transaction",
      FRAUD_SECURITY: "Piragtage / Sarqa",
      ACCOUNT: "Compte ta3i",
      LOAN_CONTRACT: "Duyun & Contracts",
      TECH_ISSUE: "Bug f'App",
      REPORT_USER: "Signaler wahed",
      KYC_UPDATE: "Wtha2iq / KYC",
      GENERAL: "Mossa3ada"
    }
  }
};